services:
  db:
    image: mysql:8.0-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:
